name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.2.1
  - pandas-profiling
  - ydata-profiling
  - pyarrow=12.0.1
  - pip:
      - wandb==0.15.12
